In [1]:
# Example bitshuffle compression

In [2]:
# Create random data
import numpy
array = numpy.random.rand(100, 100)
array = array.astype('float32')

In [3]:
array

array([[ 0.35555062,  0.72370034,  0.56636184, ...,  0.13906424,
         0.41080284,  0.66199255],
       [ 0.60582209,  0.37987518,  0.18578379, ...,  0.84882295,
         0.54763156,  0.54685247],
       [ 0.33031824,  0.52922076,  0.23738767, ...,  0.66041476,
         0.10677683,  0.63404685],
       ..., 
       [ 0.26236001,  0.42673022,  0.67775303, ...,  0.8188948 ,
         0.32254988,  0.61050385],
       [ 0.4466939 ,  0.12097479,  0.96123821, ...,  0.3269417 ,
         0.66937703,  0.11849337],
       [ 0.88062376,  0.06722216,  0.96908993, ...,  0.51209027,
         0.64907885,  0.62801409]], dtype=float32)

In [4]:
array.nbytes

40000

In [5]:
import bitshuffle

In [6]:
# Use bitshuffle lz4 compression method (does shuffling itselve)
compressed_d = bitshuffle.compress_lz4(array)

In [7]:
compressed_d.nbytes

33152

In [8]:
# Display the first 30 characters of the compressed bytes
compressed_d[:31]

array([  0,   0,  26, 127, 245, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255], dtype=uint8)

In [9]:
array_uncompressed = bitshuffle.decompress_lz4(compressed_d, (100,100), numpy.dtype('float32'))

In [10]:
array_uncompressed

array([[ 0.35555062,  0.72370034,  0.56636184, ...,  0.13906424,
         0.41080284,  0.66199255],
       [ 0.60582209,  0.37987518,  0.18578379, ...,  0.84882295,
         0.54763156,  0.54685247],
       [ 0.33031824,  0.52922076,  0.23738767, ...,  0.66041476,
         0.10677683,  0.63404685],
       ..., 
       [ 0.26236001,  0.42673022,  0.67775303, ...,  0.8188948 ,
         0.32254988,  0.61050385],
       [ 0.4466939 ,  0.12097479,  0.96123821, ...,  0.3269417 ,
         0.66937703,  0.11849337],
       [ 0.88062376,  0.06722216,  0.96908993, ...,  0.51209027,
         0.64907885,  0.62801409]], dtype=float32)

In [11]:
if (array == array_uncompressed).all():
    print('same')

same
