# Use bitshuffle compression with h5py 

In [1]:
import sys
sys.byteorder

'little'

In [2]:
import h5py
import numpy
# Need to activate bitshuffle HDF5 Plugin
import bitshuffle.h5

# Print h5py version
print(h5py.__version__) # '2.X.Y'

filename = 'test_bitshuffle.hdf5'
filehandle = h5py.File(filename, "w")

2.7.0


In [3]:
## dataset = filehandle.create_dataset("data", (100, 100, 100), maxshape=(None, 100, 100), chunks=(1,100,100))
block_size = 2048
dataset = filehandle.create_dataset("data", (100, 100, 100), maxshape=(None, 100, 100), compression=bitshuffle.h5.H5FILTER, compression_opts=(block_size, bitshuffle.h5.H5_COMPRESS_LZ4), chunks=(1,100,100), dtype='float32')
# The compression id can also be specified as such: compression=bitshuffle.h5.H5FILTER

In [4]:
# Create random numbers
array = numpy.random.rand(100, 100)
array = array.astype('float32')

In [5]:
array

array([[ 0.76599908,  0.08087604,  0.89015293, ...,  0.71580678,
         0.50043029,  0.00294846],
       [ 0.59136188,  0.28044301,  0.78091282, ...,  0.65266222,
         0.77106023,  0.40423301],
       [ 0.14480616,  0.85435981,  0.4379763 , ...,  0.45012942,
         0.10004418,  0.83703011],
       ..., 
       [ 0.76340526,  0.88050568,  0.49160603, ...,  0.20831208,
         0.82347405,  0.34274569],
       [ 0.5938369 ,  0.6565693 ,  0.04654337, ...,  0.21290956,
         0.94102037,  0.41774505],
       [ 0.20256165,  0.05428438,  0.15758543, ...,  0.79733545,
         0.16817223,  0.42660627]], dtype=float32)

In [6]:
dataset[0]=array

In [7]:
dataset[0]

array([[ 0.76599908,  0.08087604,  0.89015293, ...,  0.71580678,
         0.50043029,  0.00294846],
       [ 0.59136188,  0.28044301,  0.78091282, ...,  0.65266222,
         0.77106023,  0.40423301],
       [ 0.14480616,  0.85435981,  0.4379763 , ...,  0.45012942,
         0.10004418,  0.83703011],
       ..., 
       [ 0.76340526,  0.88050568,  0.49160603, ...,  0.20831208,
         0.82347405,  0.34274569],
       [ 0.5938369 ,  0.6565693 ,  0.04654337, ...,  0.21290956,
         0.94102037,  0.41774505],
       [ 0.20256165,  0.05428438,  0.15758543, ...,  0.79733545,
         0.16817223,  0.42660627]], dtype=float32)

In [8]:
filehandle.close()

In [9]:
filehandle = h5py.File(filename, "r")

In [10]:
filehandle['data'][0]

array([[ 0.76599908,  0.08087604,  0.89015293, ...,  0.71580678,
         0.50043029,  0.00294846],
       [ 0.59136188,  0.28044301,  0.78091282, ...,  0.65266222,
         0.77106023,  0.40423301],
       [ 0.14480616,  0.85435981,  0.4379763 , ...,  0.45012942,
         0.10004418,  0.83703011],
       ..., 
       [ 0.76340526,  0.88050568,  0.49160603, ...,  0.20831208,
         0.82347405,  0.34274569],
       [ 0.5938369 ,  0.6565693 ,  0.04654337, ...,  0.21290956,
         0.94102037,  0.41774505],
       [ 0.20256165,  0.05428438,  0.15758543, ...,  0.79733545,
         0.16817223,  0.42660627]], dtype=float32)

In [11]:
filehandle['data'][0].shape

(100, 100)

In [12]:
filehandle['data']._filters

{'32008': (0, 2, 4, 2048, 2)}

In [13]:
filehandle['data'].shuffle

False

In [14]:
# Checking for sameness
if (array == filehandle['data'][0]).all():
    print('same')

same
