# Simple direct chunk write

In [1]:
import h5py
import numpy

In [2]:
filename = "test_direct_chunk_write.hdf5"
filehandle = h5py.File(filename, "w")

In [3]:
dataset = filehandle.create_dataset("data", (100, 100, 100), maxshape=(None, 100, 100), chunks=(1,100,100), dtype='float32')

In [4]:
array = numpy.random.rand(100, 100)
array = array.astype('float32')

In [5]:
array

array([[ 0.43470463,  0.91931921,  0.95955473, ...,  0.04316058,
         0.89442378,  0.8886199 ],
       [ 0.69513589,  0.16089617,  0.49597403, ...,  0.70610487,
         0.89237285,  0.12920372],
       [ 0.96914262,  0.02483979,  0.89165074, ...,  0.20154211,
         0.10625901,  0.08401911],
       ..., 
       [ 0.08059023,  0.14494771,  0.6120857 , ...,  0.47727132,
         0.5210517 ,  0.80569118],
       [ 0.85813099,  0.60863936,  0.90519196, ...,  0.16949967,
         0.82091773,  0.10137654],
       [ 0.8964538 ,  0.43340129,  0.24802384, ...,  0.30881295,
         0.2869752 ,  0.35428736]], dtype=float32)

In [6]:
dataset._filters

{}

In [7]:
# Direct chunk write
index = 0
dataset.id.write_direct_chunk((index, 0, 0), array.tobytes(), filter_mask=1)

In [8]:
dataset[0]

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [9]:
# File need to be closed to have the changes been visible
filehandle.close()

In [10]:
filehandle = h5py.File(filename, "r")

In [11]:
filehandle['data'][0]

array([[ 0.43470463,  0.91931921,  0.95955473, ...,  0.04316058,
         0.89442378,  0.8886199 ],
       [ 0.69513589,  0.16089617,  0.49597403, ...,  0.70610487,
         0.89237285,  0.12920372],
       [ 0.96914262,  0.02483979,  0.89165074, ...,  0.20154211,
         0.10625901,  0.08401911],
       ..., 
       [ 0.08059023,  0.14494771,  0.6120857 , ...,  0.47727132,
         0.5210517 ,  0.80569118],
       [ 0.85813099,  0.60863936,  0.90519196, ...,  0.16949967,
         0.82091773,  0.10137654],
       [ 0.8964538 ,  0.43340129,  0.24802384, ...,  0.30881295,
         0.2869752 ,  0.35428736]], dtype=float32)

In [12]:
filehandle['data']._filters

{}

In [13]:
filehandle['data'][0].shape

(100, 100)

In [14]:
# Checking for sameness
if (array == filehandle['data'][0]).all():
    print('same')

same
